### ISSUE TITLE
mail doesnt work

### ISSUE THREAD

**Issue by Bentechy66** [ractf/infrastructure#183]
**Describe the bug**
mail doesnt work

**To Reproduce**
1. try to use mail

**Expected behavior**
mail works

**Screenshots**
![image](https://user-images.githubusercontent.com/19192864/110189428-f2a1c380-7e16-11eb-99db-313f1e77d507.png)

**Additional context**
kerchow

**Comment by thebeanogamer** [comment]
Please email your concerns to <support@reallyawesome.atlassian.net>

**Comment by david-cooke** [comment]
@thebeanogamer this is an urgent issue that needs fixing immediately
